event:
    pattern:  /
    defaults: { _controller: "EventBundle:Event:index" }

event_calendar:
    pattern:  /calendar
    defaults: { _controller: "EventBundle:Event:calendar" }

event_show:
    pattern:  /{id}/show
    defaults: { _controller: "EventBundle:Event:show" }

event_new:
    pattern:  /new
    defaults: { _controller: "EventBundle:Event:new" }

event_create:
    pattern:  /create
    defaults: { _controller: "EventBundle:Event:create" }
    requirements: { _method: post }

event_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EventBundle:Event:edit" }

event_update:
    pattern:  /{id}/update
    defaults: { _controller: "EventBundle:Event:update" }
    requirements: { _method: post|put }

event_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EventBundle:Event:delete" }
    requirements: { _method: post|delete }
    
event_past:
    pattern:  /participation
    defaults: { _controller: "EventBundle:Event:listEventPast" }

event_past_ajax:
    pattern:  /{firstResult}/{maxResults}/participation/ajax
    defaults: { _controller: "EventBundle:Event:listEventPastAjax" }

event_next:
    pattern:  /next
    defaults: { _controller: "EventBundle:Event:listEventNext" }

event_next_ajax:
    pattern:  /{firstResult}/{maxResults}/next/ajax
    defaults: { _controller: "EventBundle:Event:listEventNextAjax" }
    
event_create_punctuation:
    pattern:  /{idEvent}/create_punctuation
    defaults: { _controller: "EventBundle:Event:createPunctuation" }

event_next_all:
    pattern:  /{firstResult}/{maxResults}/event/next/ajax/all
    defaults: { _controller: "EventBundle:Event:nextEventAllAjax" }

event_next_all_rss:
    pattern:  /{firstResult}/{maxResults}/event/next/rss/all
    defaults: { _controller: "EventBundle:Event:nextEventAllRss" }   


event_next_min:
    pattern:  /{firstResult}/{maxResults}/event/next/reduce
    defaults: { _controller: "EventBundle:Event:nextEventReduce" }

event_next_min_sport:
    pattern:  /{idSport}/{firstResult}/{maxResults}/event/next/reduce
    defaults: { _controller: "EventBundle:Event:nextEventBySportReduce" }

event_search:
    pattern:  /event/search
    defaults: { _controller: "EventBundle:Event:searchEventReduce" }

event_list_next:
    pattern:  /event/next/all
    defaults: { _controller: "EventBundle:Event:listNexEvent" }
    
asigne_result:
    pattern:  /asigne/{idEvent}/{idClassification}/result
    defaults: { _controller: "EventBundle:Event:asigneResultEvent" }

search_result:
    pattern:  /search/result
    defaults: { _controller: "EventBundle:Event:searchResult" }

notificacion_result:
    pattern:  /notificacion/result
    defaults: { _controller: "EventBundle:Event:notificationResult" }
    
enrolled_update:
    pattern:  /enrolled/{id}/update
    defaults: { _controller: "EventBundle:Event:updateEnrolled" }
  
enrolled_new:
    pattern:  /enrolled/{idEvent}/new
    defaults: { _controller: "EventBundle:Event:newEnrolled" } 
     
enrolled_edit:
    pattern:  /enrolled/{id}/edit
    defaults: { _controller: "EventBundle:Event:editEnrolled" } 
    
list_classification:
    pattern:  /{firstResult}/{maxResults}/classification/{idEvent}/list/{tipe}
    defaults: { _controller: "EventBundle:Event:getClassificationByIdEvent" }    
    
event_rearch_result:
    pattern:  /search/{search}/result/{idEvent}
    defaults: { _controller: "EventBundle:Event:searchResultByNameAndBib" } 

event_report_running:
    pattern:  /{userId}/reports/running
    defaults: { _controller: "EventBundle:EventReports:generateReportUserRunning" } 
    
event_send_point:
    pattern:  /{latitude}/geo/{longitude}/map/{time}/point/{user}/{idEvent}
    defaults: { _controller: "EventBundle:Event:createEventPoint" } 
    
event_today: 
    pattern:  /today
    defaults: { _controller: "EventBundle:Event:getToDayEvents" } 
    
event_online_user:
    pattern:  /online/{id}/user/{name}
    defaults: { _controller: "EventBundle:Event:onlineEventUser" } 

event_online_generate:
    pattern:  /online/{idEvent}/generate
    defaults: { _controller: "EventBundle:Event:generateIdOnline" } 

 
event_show_event:
    pattern:  /show/map/{name}/{idEvent}/online
    defaults: { _controller: "EventBundle:Event:showEventMap" } 
 
event_last_result:
    pattern:  /last/{firstResult}/{maxResults}/result
    defaults: { _controller: "EventBundle:Event:lastResultEvent" } 

event_list_without_result:
    pattern:  /last/without/result/list
    defaults: { _controller: "EventBundle:Event:listEventWithOutResultEvent" } 
   
event_without_result:
    pattern:  /last/without/{firstResult}/{maxResults}/result/load
    defaults: { _controller: "EventBundle:Event:lastEventWithOutResultEvent" } 
    
event_result_preview:
    pattern:  /{id}/preview
    defaults: { _controller: "EventBundle:Event:preViewResult" }
    requirements: { _method: post|put }
    
event_result_admin:
    pattern:  /{id}/result/admin
    defaults: { _controller: "EventBundle:Event:adminResult" }

event_enviar_email:
    pattern:  /enviaremail
    defaults: { _controller: "EventBundle:Event:enviarEmailEvento" }
    
event_distance:
    pattern:  /distance/map/{name}/{idEvent}/online
    defaults: { _controller: "EventBundle:Event:getEstadisticasEventOnline" }

event_interval:
    pattern:  /interval/map/{name}/{idEvent}/online
    defaults: { _controller: "EventBundle:Event:getIntervalEventOnline" }
    
event_lastpoint:
    pattern:  /last/point/{name}/{idEvent}/online
    defaults: { _controller: "EventBundle:Event:getLastPointEvent" }

event_around_my:
    pattern:  /around
    defaults: { _controller: "EventBundle:Event:eventAroundMy" }
    
event_by_organizer:
    pattern:  /{firstResult}/{maxResults}/{organizer}/organizer
    defaults: { _controller: "EventBundle:Event:listEventByOrganizer" }
    
event_show_classification:
    pattern:  /classification/{idClassification}/show
    defaults: { _controller: "EventBundle:Event:showClassification" }




    
    
    
