Category:
    type: entity
    table: category
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 300
            fixed: false
            nullable: true
        code:
            type: string
            length: 20
            fixed: false
            nullable: true
        eventId:
            type: integer
            unsigned: false
            nullable: false
            column: event_id
        isGlobal:
            type: boolean
            nullable: true
            column: is_global
    lifecycleCallbacks: {  }
