Amateur\ObjectBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: Amateur\ObjectBundle\Entity\UserRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        username:
            type: string
            length: 16
            fixed: false
            nullable: false
        email:
            type: string
            length: 255
            fixed: false
            nullable: false
        createTime:
            type: datetime
            nullable: true
            column: create_time
        salt:
            type: string
            length: 32
            fixed: false
            nullable: true
        password:
            type: string
            length: 100
            fixed: false
            nullable: true
        isactive:
            type: boolean
            nullable: true
            column: isActive
        name:
            type: string
            length: 300
            fixed: false
            nullable: true
        lastname:
            type: string
            length: 300
            fixed: false
            nullable: true
        codePassword:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: code_password
        photo:
            type: string
            length: 500
            fixed: false
            nullable: true
        tyc:
            type: boolean
            nullable: true
        language:
            type: string
            length: 20
            fixed: false
            nullable: true
        lastUpdateDate:
            type: datetime
            nullable: true
            column: last_update_date
        isOnline:
            type: boolean
            nullable: true
            column: is_online
        tipeUser:
            type: string
            length: 20
            fixed: false
            nullable: true
            column: tipe_user
    lifecycleCallbacks: {  }
